baseURL = "https://blog.batkiz.com/"
languageCode = "zh-hans"
defaultContentLanguage = "zh-hans"
title = "not b@tk1z"
theme = "fs"
hasCJKLanguage = true
enableEmoji = true
enableRobotsTXT = true

# googleAnalytics = "UA-111900041-1"
[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = 0.5

[Permalinks]
posts = "/posts/:year/:filename/"

[markup]

[markup.highlight]
codeFences = false

[menu]

[[menu.main]]
name = "Posts"
url = "/posts/"
weight = 1

[[menu.main]]
name = "Tags"
url = "/tags/"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "RSS"
url = "/atom.xml"
weight = 4

[params]
since = 2017
author = "batkiz" # Author's name
subtitle = "一帘新语随风去，半山明月踏江来。" # Subtitle
# cloudflareWebAnalyticsToken = ""
google_verification = ""
bing_verification = ""
avatar = "https://s2.ax1x.com/2019/10/21/KQ5y0e.jpg" #comment it to use gravatar
socialShare = false
description = "" # site description
keywords = "" # site keywords
license = '<a href="https://creativecommons.org/licenses/by-nc-sa/4.0/" target="_blank">CC BY-NC-SA 4.0</a>'
licenseText = '转载或引用本文时请遵守许可协议，注明原文作者、链接，不得用于商业用途'

[params.social]
GitHub = "batkiz"
Twitter = "batkizc"
Email = "batkiz@outlook.com"
Telegram = "batkiz"

[outputs]
home = ["Atom", "HTML"]

[outputFormats.Atom]
mediatype = "application/rss"
baseName = "atom"

[author]
name = "batkiz"
